version: '3'
services:
  app:
    build:
      context: ./docker/app
    tty: true
    environment:
      TZ: Asia/Tokyo
    volumes:
      - .:/root/project
  tfb-database-my:
    image: mariadb
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hello_world
      MYSQL_USER: benchmarkdbuser
      MYSQL_PASSWORD: benchmarkdbpass
      TZ: Asia/Tokyo
    # volumes:
    #   - ./docker/mysql_entrypoint:/docker-entrypoint-initdb.d
  tfb-database-pg:
    image: postgres:alpine
    tty: true
    environment:
      POSTGRES_DB: hello_world
      POSTGRES_USER: benchmarkdbuser
      POSTGRES_PASSWORD: benchmarkdbpass
      TZ: Asia/Tokyo
    volumes:
      - ./docker/postgres_entrypoint:/docker-entrypoint-initdb.d